from typing import Any, Protocol


class UserRepositoryPort(Protocol):
    def find_by_id(self, user_id: int) -> Any | None: ...
    def find_by_email(self, email: str) -> Any | None: ...
    def find_by_cedula(self, cedula: str) -> Any | None: ...
    def find_role_by_name(self, name: str) -> Any | None: ...
    def list_users(self, search: str | None = None, is_active: bool | None = None) -> list[Any]: ...
    def create_user(self, data: dict[str, Any], role: Any, password_hash: str) -> Any: ...
    def save(self, user: Any) -> Any: ...


class PasswordResetRepositoryPort(Protocol):
    def create(self, user_id: int, token: str, expires_at: Any) -> Any: ...
    def find_by_token(self, token: str) -> Any | None: ...
    def save(self, reset_entry: Any) -> Any: ...


class AnnouncementRepositoryPort(Protocol):
    def create(self, data: dict[str, Any], published_by: int) -> Any: ...
    def find_by_id(self, announcement_id: int) -> Any | None: ...
    def list_announcements(
        self,
        categories: list[str] | None = None,
        search: str | None = None,
        include_inactive: bool = False,
    ) -> list[Any]: ...
    def save(self, announcement: Any) -> Any: ...


class NotificationRepositoryPort(Protocol):
    def create_for_active_users(self, announcement: Any, announcement_type: str) -> None: ...
    def list_for_user(self, user_id: int, unread_only: bool = False) -> list[Any]: ...
    def count_unread(self, user_id: int) -> int: ...
    def find_for_user(self, notification_id: int, user_id: int) -> Any | None: ...
    def save(self, notification: Any) -> Any: ...
    def mark_all_as_read(self, user_id: int) -> None: ...


class DocumentRepositoryPort(Protocol):
    def list_documents(self) -> list[Any]: ...
    def create(self, filename: str, file_path: str, uploaded_by_id: int) -> Any: ...
    def find_by_id(self, document_id: int) -> Any | None: ...
    def save(self, document: Any) -> Any: ...
    def delete(self, document: Any) -> None: ...
    def delete_chunks_by_document_name(self, document_name: str) -> None: ...
