import os

EMBEDDING_MODEL = "intfloat/multilingual-e5-large"
VECTOR_DIMENSION = 1024

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
MAX_DOCUMENT_SIZE_MB = 20
MAX_DOCUMENT_SIZE_BYTES = MAX_DOCUMENT_SIZE_MB * 1024 * 1024

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "groq")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

RESET_TOKEN_EXPIRE_HOURS = 24